server:
  servlet:
    context-path: /weather-monitor

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db_weather_monitor?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8
    username: root
    password: zeng0093
  data:
    redis:
      host: localhost
      port: 6379
      database: 0
      connect-timeout: 10s

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
  mapper-locations: classpath*:/mapper/**Mapper.xml
  global-config:
    db-config:
      logic-delete-field: delFlag
      logic-delete-value: 1
      logic-not-delete-value: 0
      id-type: auto

config:
  jwt:
    # 加密密钥
    secret: emVuZ3h1ZWJpbiBmYWxsIGluIGxvdmUgbHVveXVoYW8=
    # token 有效时长(默认24小时)
    expire: 86400000
    # header名称
    header: Authorization

project:
  # 名称
  name: weather-monitor
  # 版本
  version: 1.0.0
  # 版权年份
  copyrightYear: 2023
